/* global window */
// İSMET İLE MATEMATİK — içerik verisi
// Tüm içerik tek yerden; bileşenler window.DATA üzerinden okur.

const CATEGORIES = [
  { id: "hepsi", label: "Hepsi" },
  { id: "tyt", label: "TYT" },
  { id: "ayt", label: "AYT" },
  { id: "lgs", label: "LGS" },
  { id: "kpss", label: "KPSS" },
  { id: "uni", label: "Üniversite" },
  { id: "olimpiyat", label: "Olimpiyat" },
];

// thumb: dekoratif "video kapağı" için gradient + sembol
const COURSES = [
  {
    id: "tyt-sifir",
    title: "TYT Matematik · Sıfırdan Zirveye",
    cat: "tyt",
    level: "Başlangıç",
    hours: 42,
    lessons: 186,
    rating: 4.9,
    students: 18420,
    price: 749,
    oldPrice: 1499,
    symbol: "∑",
    g1: "#c8ff2e", g2: "#1f8a5b",
    tag: "ÇOK SATAN",
    new: false,
    video: {
      src: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
      poster: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=900&q=80"
    },
  },
  {
    id: "ayt-pro",
    title: "AYT Matematik PRO · Türev & İntegral",
    cat: "ayt",
    level: "İleri",
    hours: 56,
    lessons: 214,
    rating: 4.9,
    students: 12030,
    price: 899,
    oldPrice: 1799,
    symbol: "∫",
    g1: "#7c5cff", g2: "#2b1f6b",
    tag: "ÇOK SATAN",
    new: false,
  },
  {
    id: "geo-hiz",
    title: "Geometri · Hızlı Çözüm Teknikleri",
    cat: "ayt",
    level: "Orta",
    hours: 28,
    lessons: 132,
    rating: 4.8,
    students: 8740,
    price: 549,
    oldPrice: 999,
    symbol: "△",
    g1: "#38e1ff", g2: "#0b4f63",
    tag: null,
    new: true,
  },
  {
    id: "lgs-kamp",
    title: "LGS Matematik · 8. Sınıf Kampı",
    cat: "lgs",
    level: "Orta",
    hours: 34,
    lessons: 158,
    rating: 4.9,
    students: 9610,
    price: 599,
    oldPrice: null,
    symbol: "π",
    g1: "#ff7ac8", g2: "#6b1f4d",
    tag: null,
    new: true,
  },
  {
    id: "problem-mantik",
    title: "Problemler & Mantık · Sözel Çözüm",
    cat: "tyt",
    level: "Başlangıç",
    hours: 22,
    lessons: 96,
    rating: 4.7,
    students: 7120,
    price: 449,
    oldPrice: 899,
    symbol: "≠",
    g1: "#ffd23f", g2: "#7a5a06",
    tag: null,
    new: false,
  },
  {
    id: "kpss-mat",
    title: "KPSS Matematik · Garanti Net",
    cat: "kpss",
    level: "Orta",
    hours: 38,
    lessons: 170,
    rating: 4.8,
    students: 5340,
    price: 649,
    oldPrice: 1299,
    symbol: "%",
    g1: "#c8ff2e", g2: "#3a5a0c",
    tag: null,
    new: false,
  },
  {
    id: "calculus",
    title: "Üniversite Calculus 101",
    cat: "uni",
    level: "İleri",
    hours: 48,
    lessons: 142,
    rating: 4.9,
    students: 3980,
    price: 799,
    oldPrice: null,
    symbol: "ƒ",
    g1: "#7c5cff", g2: "#1a3a6b",
    tag: null,
    new: true,
  },
  {
    id: "lineer-ai",
    title: "Yapay Zeka için Lineer Cebir",
    cat: "uni",
    level: "İleri",
    hours: 31,
    lessons: 118,
    rating: 4.9,
    students: 4560,
    price: 849,
    oldPrice: 1699,
    symbol: "⊗",
    g1: "#38e1ff", g2: "#3b1f6b",
    tag: "YENİ NESİL",
    new: true,
  },
  {
    id: "olimpiyat",
    title: "Olimpiyat Matematiği · Sayılar Teorisi",
    cat: "olimpiyat",
    level: "Usta",
    hours: 40,
    lessons: 88,
    rating: 5.0,
    students: 1290,
    price: 999,
    oldPrice: null,
    symbol: "∞",
    g1: "#ff7ac8", g2: "#3a0c2c",
    tag: "USTA",
    new: false,
  },
];

// Canlı eğitim takvimi
const CALENDAR = [
  { id: "c1", day: 12, month: "HAZ", weekday: "Per", title: "AYT Türev Maratonu", time: "20:00", type: "Canlı", seats: 8, cat: "ayt" },
  { id: "c2", day: 15, month: "HAZ", weekday: "Paz", title: "TYT Soru Çözüm Kampı", time: "14:00", type: "Canlı", seats: 23, cat: "tyt" },
  { id: "c3", day: 19, month: "HAZ", weekday: "Per", title: "LGS Deneme Analizi", time: "19:30", type: "Webinar", seats: 41, cat: "lgs" },
  { id: "c4", day: 24, month: "HAZ", weekday: "Çar", title: "Geometri Pratik Atölyesi", time: "21:00", type: "Atölye", seats: 5, cat: "ayt" },
  { id: "c5", day: 28, month: "HAZ", weekday: "Paz", title: "Üniversiteye Hazırlık Soru-Cevap", time: "13:00", type: "Webinar", seats: 60, cat: "uni" },
];

// Müşteri / öğrenci referansları
const TESTIMONIALS = [
  { id: "t1", name: "Zeynep A.", role: "TYT 2025 · 38 net", quote: "Matematikten korkardım, şimdi en sevdiğim ders. İsmet hocanın anlatımı sıfırdan her şeyi oturtuyor.", rating: 5, color: "#c8ff2e" },
  { id: "t2", name: "Mert K.", role: "AYT · Boğaziçi", quote: "Türev-integral kısmında resmen sınıf atladım. Canlı yayınlardaki soru çözümleri altın değerinde.", rating: 5, color: "#7c5cff" },
  { id: "t3", name: "Elif D.", role: "LGS · Fen Lisesi", quote: "8. sınıf kampıyla dönem boyu hiç geri kalmadım. Kartlardan takvimi takip etmek süper pratik.", rating: 5, color: "#38e1ff" },
  { id: "t4", name: "Burak T.", role: "Üniversite · Yazılım", quote: "Lineer cebir dersi yapay zekaya geçişimi kolaylaştırdı. Platform tasarımı da bir o kadar temiz.", rating: 5, color: "#ff7ac8" },
];

// Şirket / kurum referansları — jenerik (telifsiz) wordmark'lar
const LOGOS = [
  { id: "l1", name: "EduMax", kind: "word" },
  { id: "l2", name: "Kampüs+", kind: "word" },
  { id: "l3", name: "ZekiAkademi", kind: "dot" },
  { id: "l4", name: "BilgeİŞ", kind: "word" },
  { id: "l5", name: "MathLab", kind: "bracket" },
  { id: "l6", name: "ÖğrenHub", kind: "dot" },
];

const STATS = [
  { id: "s1", value: "52K+", label: "Öğrenci" },
  { id: "s2", value: "4.9", label: "Ortalama puan" },
  { id: "s3", value: "340+", label: "Saat içerik" },
  { id: "s4", value: "18", label: "Eğitim" },
];

window.DATA = { CATEGORIES, COURSES, CALENDAR, TESTIMONIALS, LOGOS, STATS };
